### ISSUE TITLE
LGTM tests not working

### ISSUE THREAD

**Issue by MatthiasWM** [pguyot/Einstein#106]
LGTM was configured at lgtm.com to verify our code by one of the admins. This is a nice idea, but currently, our code quality s rated D, which I find rather unjustified. The problem ist, that LGTM doesn't;t even run all the way through its tests, because it tries to build with FLTK 1.3, which is no longer possible. FLTK 1.4 is required.

Now we need to either modify the LGTM master settings, which I have no access to, or write a .lgtm.yml file in the root directory to explain to LGTM what exactly it should test.

Since I am afraid that we have no lgtm expert in the developer list here, I'll probably end up learning that file format and do it, simply because I can't stand having out project "fail" tests that are not actually tested. And I really do not want to have a D rating for my code quality!

**Comment by ekoeppen** [comment]
Another option might be to take clang-tidy into use, it has a very simple CMake integration, and would check the code as CMake sees it.

Eckhart

**Comment by pguyot** [comment]
I am confused about why LGTM fetches FLTK 1.3 instead of 1.4. I am no LGTM expert but probably is the guilty one who enabled it and can try and fix the configuration.

**Comment by MatthiasWM** [comment]
Maybe they mean well, because FLTK 1.3 is the official release. But the release scheme of FLTK is terrible, and 1.3 is very outdated (no HiDPI support for a start), and 1.4 is very stable. At GitHub, it would have to check out the master branch instead of 1.3.8 .

Sorry for my rant, didn't;t mean to complain about LGTM integration itself, which is a very good thing.

**Comment by MatthiasWM** [comment]
See Build Request #109.

**Comment by pguyot** [comment]
Solved in #111 which is based on #109
