### ISSUE TITLE
macos_fltk CI randomly fails

### ISSUE THREAD

**Issue by pguyot** [pguyot/Einstein#116]
Compare these two builds:
https://github.com/pguyot/Einstein/runs/4720316267?check_suite_focus=true
https://github.com/pguyot/Einstein/runs/4720452346?check_suite_focus=true

**Comment by MatthiasWM** [comment]
Yes, thank you. I may have introduced a bug into Fluid, the user interface design tool that translates .fl files into C++. This is an urgent fix for the entire FLTK tree.
