### ISSUE TITLE
How can I build FLTK version of Einstein?

### ISSUE THREAD

**Issue by INDIGI-CO-UK** [pguyot/Einstein#126]
I'm trying to build FLTK version, but I'm getting MacOS interface version without all new features that Matthias implemented in Einstein.

I'm a noob. Please advice :)

Cheers,
Pawel

**Comment by MatthiasWM** [comment]
Build instructions are in the file "BUILDING.md" under 
https://github.com/pguyot/Einstein/blob/master/BUILDING.md

**Comment by MatthiasWM** [comment]
I will build and release a MacOS preview soon. I will probably be able to compile for Linux, but the Windows version may not compile on an M1 Mac, so I;ll have to wait until I get my hands on an Intel Windows machine in a week or so.

**Comment by INDIGI-CO-UK** [comment]
I did everything from BUILDING.md

I was able to build a version for Big Sur, but that version will not work on Mojave. So, I tried to build for Mojave (10.14), but I'm getting one error (see screenshot).

How can I fix it?

<img width="1512" alt="Screenshot 2022-01-08 at 17 48 09" src="https://user-images.githubusercontent.com/11366655/148654603-00d31003-338d-4982-bd3a-97ba72d9d7b9.png">

**Comment by MatthiasWM** [comment]
Yes, this was just introduced by a change that Paul made and was fixed a few hours later. Go into the Xcode main menu, "[Source Control] >> [Pull..]", if will update to the newest version. Then press ⌘-R, and it should compile and run.

> On 8. Jan 2022, at 18:59, Pawel Piotrowski ***@***.***> wrote:
> 
> 
> I did everything from BUILDING.md
> 
> I was able to build a version for Big Sur, but that version will not work on Mojave. So, I tried to build for Mojave (10.14), but I'm getting one error (see screenshot).
> 
> How can I fix it?
> 
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.
> 

Mit freundlichen Grüssen,

 Matthias Melcher

---
Geschäftsführer

M.Melcher GmbH
Hohenbudberger Strasse 4-10
47829 Krefeld Uerdingen

***@***.***

Fon +49 2151 4832 26
Fax +49 2151 4832 38

**Comment by MatthiasWM** [comment]
I have added some additional trickery to make Einstein run on all machines starting with 10.9 Mavericks and Intel and Apple Silicon. Please try here: http://messagepad.org/Downloads/Einstein/MacOS/Einstein.MacOS.2022.5.0.zip and let me know if it works for you. Thanks.

**Comment by INDIGI-CO-UK** [comment]
That version is working great on Mojave. Thank you. I have the macOS interface version on Mojave working too.

**Comment by MatthiasWM** [comment]
Phew, great! Thanks for letting me know.
