### ISSUE TITLE
Install Einstein on Zaurus SL-5500 for noobs...

### ISSUE THREAD

**Issue by INDIGI-CO-UK** [pguyot/Einstein#14]
Guys, I'm sorry for OT, but can I ask you kindly for help with install Einstein on Zaurus SL-5500? I'm total noob. I don't know how to even start with this. Is there any system image file to just copy on Zaurus, or something like this?

Thank you,
Pawel

**Comment by morgant** [comment]
@INDIGI-CO-UK It looks like the [OpenZaurus Build Instructions](https://github.com/pguyot/Einstein/wiki/Open-Zaurus-Build-Instructions) did get migrated over from the Google Code wiki, though I doubt they've been tested in years. Seeing if it can still be built would be the starting place.

**Comment by panicsteve** [comment]
Short version: I think @pguyot might be the only person to ever successfully run Einstein on a Zaurus, and that was in 2007.  :)

I did a little tinkering recently with the ARM Linux build, trying to get it to run on a Raspberry Pi 3.  It was a bit out of my league, as I am only passingly familiar with Linux.  I eventually got it to build with a lot of hackery, but it won't boot the virtual Newton.  It pops open a window and hangs.  (In fact, it behaves similarly to the optimized Mac release build, come to think of it...  Could be the same issue that @morgant reported.)

**Comment by splorp** [comment]
> I think @pguyot might be the only person to ever successfully run Einstein on a Zaurus, and that was in 2007.

It was [2006](https://www.flickr.com/photos/splorp/87917187/), actually.

![image](https://cloud.githubusercontent.com/assets/29835/21333238/af33b40e-c60b-11e6-8b57-06aae826251b.png)

**Comment by INDIGI-CO-UK** [comment]
Guys, the problem is that, I don't even understand what that Build Instructions say. I'm completely 100% noob.

And the second problem is that, I couldn't find any working website with OpenZaurus system to download. OpenZaurus not working, Sharp developer site is off. So, I think only person who have somewhere kind of img file with working system can help.

**Comment by chuma** [comment]
Hrm.  If I can convince my dad to give me his old SL-5500, currently collecting dust in his basement, I might be able to hack on this.

**Comment by INDIGI-CO-UK** [comment]
> On 10 Feb 2017, at 14:33, Victor <notifications@github.com> wrote:
> Hrm. If I can convince my dad to give me his old SL-5500, currently collecting dust in his basement, I might be able to hack on this.
> 

Hi Victor,

That could be great!

There is problem with software for Zaurus. All websites are usually down or not active. I can’t even find normal apps for Zaurus. I can’t find OpenZaurus software too. And without this software it is impossible to install Einstein on Zaurus… :(

I’ve tried to reach to Paul for help, but he didn’t respond :(




Best regards,
Pawel Piotrowski

NPDS Server: http://newton1.applenewton.co.uk:8079 (powered by Newton 2100)
NPDS Tracker Server: http://tracker.applenewton.co.uk:3680 <http://tracker.applenewton.co.uk:3680/> (powered by Raspberry Pi)

Instagram: https://www.instagram.com/indigi_newton/ <https://www.instagram.com/indigi_newton/>
Twitter: https://twitter.com/indigi_newton/ <https://twitter.com/indigi_newton/>

**Comment by joedemo42** [comment]
I've got OpenZaurus archived as well as two SL-5500 - so I'll give that a shot. As soon as got some time to tinker around, so don't expect results tomorrow-ish.

**Comment by INDIGI-CO-UK** [comment]
> I've got OpenZaurus archived as well as two SL-5500 - so I'll give that a shot. As soon as got some time to tinker around, so don't expect results tomorrow-ish.

That would be great, @joedemo42 !!! Thank you and I hope you will find it :)

**Comment by MatthiasWM** [comment]
The Zaurus is quite outdated. We have support for iOS and Android now. I believe we can close this issue soon, unless anyone disagrees?

**Comment by joedemo42** [comment]
Oh my.... I totally forgot about this! Sorry! Would you kindly grant me four additional weeks to try and build an Zaurus executable as promised?

**Comment by MatthiasWM** [comment]
@joedemo42 Did you ever get it to run?

**Comment by INDIGI-CO-UK** [comment]
It could be great if @joedemo42 could build Einstein working on Zaurus. Don't need to continue to maintain and develop. Just to install on Zaurus and leave it for collection :)
