### ISSUE TITLE
Create a new OS X/macOS release?

### ISSUE THREAD

**Issue by morgant** [pguyot/Einstein#15]
Now that Issue #13 is resolved & closed, so we have an optimized OS X/macOS app that builds nicely, should we tag & release a version? Is there much other experimental code that we'd want to hold off doing that for?

It'd be nice to make a release and provide a downloadable binary (I'm happy to do that, or clearly @panicsteve or others can do this as well), so more people can use & test it. I don't think being signed is necessary at this point.

**Comment by panicsteve** [comment]
I don't see why not!  It's not completely stable, but it's probably never going to be.  Better to have people actually be able to download and try it, in my opinion.

Paul versioned his releases as YEAR.MONTH.  Should we keep that going, or adopt a more traditional versioning scheme?  (This could arbitrarily be 1.0 for example.)

Once that's settled, we just have to make sure the Info.plist and about box are all in agreement with the version number, and we can do an official release.  Or at least, as official as it gets around here.  :)

**Comment by toxicgumbo** [comment]
[Symantec versioning](http://semver.org) is the more contemporary practice, though I agree arbitrary should be on the table given the release cycle and relaxed approach.  Symantec versioning might be more inviting and make more sense to those who wish to contribute small changes.

**Comment by morgant** [comment]
@panicsteve @toxicgumbo While I generally prefer semantic versioning, since the project has historically been quite experimental and slow to release, without a particularly clear roadmap that developers are sticking to, @pguyot's YYYY-MM versioning is probably still more accurate & appropriate.

**Comment by jake-b** [comment]
Thinking big: I want a versioning system that yields versions that are more awkward to say then "Mavericks"

**Comment by morgant** [comment]
@jake-b ... and more chances for mispronunciation than "Yosemite".

**Comment by panicsteve** [comment]
I agree (I think I'm agreeing) that _for this particular project_ it makes more sense to use date-based versioning, since we don't really have "milestones" that we're shooting for, and it'd be simpler to just do a release whenever things feel generally stable.

What if there's multiple releases in the same month?  The last digit could either be the day of the month, or a sequential number, in other words:

Option A 

2017.1.19 (released January 19, 2017)
2017.1.25 (released January 25, 2017)
2017.1.30 (released January 30, 2017)
2017.2.4 (released February 4, 2017)

vs.

Option B

2017.1.0 (released January 19, 2017, first release of January 2017)
2017.1.1 (released January 25, 2017)
2017.1.2 (released January 30, 2017)
2017.2.0 (released February 4, 2017, first release of February 2017)

**Comment by splorp** [comment]
I prefer option ‘B’.

Or something like _Mac OS 8.1d9 “Bride of Buster” Update “Sequoia”_ …

http://www.macintoshrepository.org/2412-mac-os-8-1-pre-releases-bride-of-buster-

**Comment by panicsteve** [comment]
Another advantage of Option B is it works if you have more than one release in a day (if, say, a release goes off the rails and we have to do a quick patch)

**Comment by MatthiasWM** [comment]
> On Jan 19, 2017, at 10:59 PM, Morgan Aldridge <notifications@github.com> wrote:
> 
> @jake-b ... and more chances for mispronunciation than "Yosemite".

"Joe-Se-Mite"? LOL

Anyway, I like the 2017.1.# scheme, where # is the release number within the month.

And yes, I think we should try a release, and it would be lovely if we could get an installable binary for every supported platform... .

 - Matthias

**Comment by panicsteve** [comment]
I've committed 2017.1.0 version numbers for macOS, iOS, and Linux targets, so all that's left is to build 'em and host 'em somewhere.

GitHub doesn't have any binary hosting options, does it?  I'd be happy to do the builds and host the binaries at stevenf.com for now, if everyone's OK with that.

I also just remembered that I have einsteindev.com that's currently doing nothing.

**Comment by morgant** [comment]
Yup, GitHub supports hosting binaries. Create a release w/name &
description, then it'll allow you to attatch additional files (beyond the
source .zip that it automatically provides).

**Comment by panicsteve** [comment]
Oh, now I see it.

I went ahead and did it... Does this look OK?

https://github.com/pguyot/Einstein/releases/tag/2017.1.0

**Comment by MatthiasWM** [comment]
Looks perfect.

MacOS version works for me on 10.12.2, but is unsigned, so it needs explicit permission to run.

Can't check the Linux build...

**Comment by splorp** [comment]
Hey @panicsteve … when you have a minute, could you post a quick [ANN] to NTLK about the new release? Ta.

**Comment by panicsteve** [comment]
@splorp Done!

I guess I'll close this for now, then?  Releases are editable, so if someone is able to produce (for example) an Android or Windows binary from the 2017.1.0 tag, we can always add that to the release.

Cool!
