### ISSUE TITLE
Looking for info on NewtonScript ROMStage slot

### ISSUE THREAD

**Issue by FrankFromPdaSoft** [pguyot/Einstein#150]
I've found Paul's file UGlue.h, which is pretty helpful. What I found there makes me think that the ROMStage slot begins with

0x0000 English Newton
0x0001 French Newton
0x0003 German Newton
0x000E Japanese Newton

Is this correct so far?

More region code info seems to be available in the file Script.h. However, as a first-time GitHub user I just failed miserably in my attempt to locate this file. Any pointer would be welcome. I'm looking for the region code constants.

Thanks

Frank

**Comment by MatthiasWM** [comment]
I am not sure what a ROMStage slot is. You can easily download the entire source code by selecting `Download ZIP` in the `Code` menu on [https://github.com/pguyot/Einstein](https://github.com/pguyot/Einstein), unpack it, and then use local tools to find text in the source code.

**Comment by FrankFromPdaSoft** [comment]
I just downloaded the source code zip file, but I can't find the file Script.h. Has it perhaps been renamed?

**Comment by FrankFromPdaSoft** [comment]
I want to extend NewtTest so it can recognize Watson units. As Paul told me a long time ago, those animals have a machine type and a ROM Version like MP2x00 US, but they have a ROM stage for French. Basically, the OS is very close to MP2x00 US (even with the version string being F-717006), with code being slightly different and many functions linked at different places because it's a totally different build.

So in order to figure out it's in fact a Watson and not a 2x00, you need to check the RomStage value. Paul pointed me to the file UGlue.cpp (https://github.com/pguyot/Einstein/blob/master/Drivers/UGlue.cpp#L69). Scipt.h is mentioned in line 57 of the associated .h file UGlue.h.

**Comment by pguyot** [comment]
The mentions of file `Script.h` in `UGlue.h` actually refers to a header that was well known in Mac programming and is now part of less used `CarbonCore` framework.

It is installed with Xcode development tools on the Mac, and you probably can find several copies online such as [this one](https://github.com/phracker/MacOSX-SDKs/blob/master/MacOSX10.6.sdk/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/Headers/Script.h#L286). This file typically lists region codes which is what `UGlue.h` [refers to](https://github.com/pguyot/Einstein/blob/master/Drivers/UGlue.h#L57).

The list of region codes is quite an old feature of MacOS. You can find it in the [volume “Text“ of Inside Macintosh series](https://vintageapple.org/inside_r/pdf/Text_1993.pdf) which was published in 1993, page 6-57. I always thought the fact that France is the second entry of this enumeration was related to the importance of the market for Apple in the early 1990s.

**Comment by MatthiasWM** [comment]
@FrankFromPdaSoft Hi Frank. Is this the information that you needed?

**Comment by FrankFromPdaSoft** [comment]
Yep, thanks. Is there something I should do to mark issues like this as solved?

**Comment by MatthiasWM** [comment]
Just close it, preferably with a short comment. Looking forward to your improved software.
