### ISSUE TITLE
Can't set NewtTest back to dates other than that of the host computer

### ISSUE THREAD

**Issue by FrankFromPdaSoft** [pguyot/Einstein#155]
## Basic Information

* Platform (64 bit Windows 7): 
* Built from source? (no): 

## Description of issue

When running Einstein 2022 4.17, I can no longer use NewtTest to set the date, neither back nor forward. The date seems to be tied to the date of the host computer. This might eventually cause problems for people who, for some Newton-related reasons, might need to set the date back to an older date at least temporarily.

## Expected behaviour

Being able to change date and time freely in the Einstein cosmos. Optionally it would be cool to provide a NewtonScript function that updates Einstein's time and date to those of the host ON REQUEST. I'd add a button into NewtTest's time and date view that is only shown when running under Einstein.

## Steps to reproduce issue

Fire up Einstein, start NewtTest, and try to change date or time.

**Comment by MatthiasWM** [comment]
I'd assume that 90% of users want the system date at all times. I am not a fan of huge Setting dialogs, but I could add a setting to not use system time at all, or to only use it to set time at boot, but allow changes later. In the long term, we need the host date system to allow long term alarms (if we ever get to that).

**Comment by FrankFromPdaSoft** [comment]
You are perfectly right. I'd assume that not 90%, but 99.99% want that. However, having fed my family for the last couple of decades by writing software that behaves locical and is easy to understand, I have learned that it is not a good idea to patronize people and claim to know better what they want than they know themselves.

If I started my Windows XP Virtual Machine now, it would allow me to set the day to any date supported by this OS regardless of the host's date. So why should this be prevented on a "Newton Virtual Machine"!

The default is good the way it is now. Let Einstein start with the host's time and date. But if the user wants to change the time in the Einstein universe, let him. He'll probably have a good reason for wanting this. It wouldn't be mandatory, but cool, if I could add a button to NewtTest that'll set Einstein's time and date back to that of the host.  For that I'll either need a way to read this data from the NewtonScript world or a function that tells Einstein to update itself., again triggered by NewtonScript.

The way ist is now, NewtTest will still allow setting time and date under Einstein, but it does no longer have any effect whatsoever. That is the kind of software that usually drives me crazy. If we decide to keep things that way, I will have to remove the whole Time & Date section from Newton when running under Einstein.

**Comment by MatthiasWM** [comment]
I apologise that my comment made you feel patronised. The feature was added by Eckhart Köppen. I was trying to be helpful by offering a solution.

**Comment by INDIGI-CO-UK** [comment]
If it is not a big problem then one additional option will be good to have. Maybe can be useful to use some specific software or during testing time/date patches in future.

Just saying :)

Cheers,
Pawel

**Comment by morgant** [comment]
I too feel it would be better to have syncing the NewtonOS time to the host's time optional, like most virtualization software does. I personally would like to update the NTP client, at some point, and being able to test in Einstein would be nice.

@INDIGI-CO-UK makes a good point about testing date/time patches in the future, though @ekoeppen's PR #144 (which also implemented the change in discussion) fixes date issues within Einstein, making patches redundant. Will that prevent us from testing future patches for physical MessagePads/eMates in Einstein or is that not much of a concern?

Regardless of the questions, many thanks to @ekoeppen for implementing these changes because they surely make Einstein much friendlier overall!

**Comment by FrankFromPdaSoft** [comment]
Matthias,
re-reading my previous post I realized that I did not express myself clearly. I'm sorry for that. There's no need for you to apologize. I didn't mean to say it was me who felt patronized. What I meant to convey was that it is not a good idea to write software in a way that makes the users of said software feel patronized. And if users are allowed to change date and time using NewtTest under Einstein, and this simply doesn't work without any explanation why, the guy who wrote NewtTest has obviously violated age-old user interface guidelines left and right. And I have only one reputation to lose :-)
We might want to continue this discussion over a beer or two...

**Comment by ekoeppen** [comment]
The issue with settings is that we have two UIs to support, the macOS one, and the FTLK one, and two ways of managing settings. And only limited developer time...

But there are two more challenging issues with using settings. Currently, the host time sync is a compile time option and not controllable at runtime, as the whole time and date management in NewtonOS is pretty complex. As you all might remember, one side effect of the 2010 bug is a never ending alarm loop. Changing the date dynamically can have some interesting side effects. Patches are also injected statically, I suppose that could be changed, but that would require some more low level changes to the patch application logic.

The other issue would be the default value, if host time sync is by default on (as that would make sense for most users), NewtTest would still not work and would at least need an additional check and warning when run under Einstein.

**Comment by FrankFromPdaSoft** [comment]
The way I understand things, the time/date patch is part of the current Einstein installation, right? If this is the case, setting the clock back from today shouldn't cause a probem?
I understand that setting it forward too much might cause a problem because at some time in the future the minute counter will roll over. Maybe this has already been taken care of by Eckharts new patch.

Be it as it may, even a problem like this wouldn'd be the end of the world if we always set the Newton's time back to the host time when Einstein is restarted.

However, if we need to decide at compile time if or if not we want host time sync, by all means keep things the way they are! It's the perfect default. But I still don't understand why AFTER compilation time changes from NewtonScript no longer work. What exactly is happening in the emulation code when someone does this? Does this NewtonScript code no longer do what it did before? Or is there some watchdog that immediately overrides such a change if it happens?
