### ISSUE TITLE
Add historical releases?

### ISSUE THREAD

**Issue by morgant** [pguyot/Einstein#16]
The Google Code project used to have downloadable binaries for various releases, but the GitHub project doesn't seem to have any tags/releases and these older binaries are no longer linked or downloadable. I'm an archivist, so I feel there's worth in preserving these old binaries, if they still exist (you never know when someone will want to try running Einstein on older OSes/hardware).

**Comment by splorp** [comment]
+1 … from another nerd with archivist tendencies.

**Comment by theredhead** [comment]
+1 from someone else who digs the idea!

On Thu, Jan 19, 2017 at 11:14 PM, Grant Hutchinson <notifications@github.com

**Comment by MatthiasWM** [comment]
Einstein was moved from GoogleCode to GitHub in July 2007. The GoogleCode archive no longer exists, making it impossible to recreate the pre-2007 releases. It may be possible to rebuild the 2007 binaries, but honestly, I am not keen on setting up a Mac with the developer tools from that time.

**Comment by splorp** [comment]
I wouldn’t want to recreate the binaries from source, either. However, I would imagine that copies of some of those old binaries still exist on people’s hard drives (or backups). If anyone comes across an old version of Einstein, why not pop it into the repo?

For example, I have binaries of the Mac OS X application with creation dates of June 22, 2010 and July 23, 2014.

Where would be a good place to archive these?

**Comment by MatthiasWM** [comment]
Sure, no problem to add those as binaries. It will not be possible to link them to a tag in the repo, obviously. Do you want me to set up a release that packs all binaries that we can find?

**Comment by splorp** [comment]
I think we just add a new directory at the root of the repo named _Archives_ and dump the binaries in there. It can function as a storage location, similar to the _Screenshots_ directory. It doesn’t need to be its own release.

We can mention the archived binaries in the read me or the wiki.

**Comment by splorp** [comment]
Ok, that makes sense.

Where would you like to start collecting the binaries?

**Comment by MatthiasWM** [comment]
Just add them here: https://github.com/pguyot/Einstein/releases/tag/PreGithubReleases

**Comment by MatthiasWM** [comment]
If this is OK for you, and you can't add binaries, just send them to me and I will add them to the page: einstein@matthiasm.com

**Comment by splorp** [comment]
No worries. I’ll add mine later today.

**Comment by splorp** [comment]
Ok, I’ve added my binaries … as well as all of the historical releases I located using the Internet Archive’s captures of @pguyot’s Kallisys site. I tried to keep the naming conventions similar to what was already in the release.

**Comment by morgant** [comment]
@splorp @MatthiasWM Many thanks, gentlemen!

**Comment by MatthiasWM** [comment]
I don't think that we will get additional releases, so I am closing this now.
