### ISSUE TITLE
Add printer support

### ISSUE THREAD

**Issue by ekoeppen** [pguyot/Einstein#165]
This is more a collection of information on how to add printer support to Einstein. The DDK has the needed headers and an example project. It might be enough to create a native protocol similar to the existing `Drivers` in the REx. It seems a tool called `Pram` is used to create some data structures which are used to construct a printer selection dialog. I suppose it would be interesting to see what that tool generates, and replicate that functionality using newt/64 or NEWT/0, or use it via mosrun.

**Comment by MatthiasWM** [comment]
2022.4.20 introduces a working printer drive on all three desktop platforms using FLTK and the modified sample drivers from the DDK. It must be compiled using MPW on Classic MacOS. I have not yet put the work in to make the driver compile on a modern host. 

The ```Pram``` tool converts the ```.pf``` file into something that can be linked into the final Package. It's a text file containing a list of printer subtypes and some additional parameters.
