### ISSUE TITLE
Allow editing the ROM file name

### ISSUE THREAD

**Issue by FrankFromPdaSoft** [pguyot/Einstein#174]
In some cases, for example when using different ROM file names that have almost the same name, it would speed things up if it was possible to edit the file name instead of having to browse it. If e. g. the last ROM file I started Einstein with was eMate0171.rom and the one I want to open now is eMate0172.rom, it would be faster if the name could simply be edited.
Admittedly this isn't much of a problem for normal Einstein users, but for people who create 10-15 new ROM files per hour...

:-)

**Comment by MatthiasWM** [comment]
Fixed in 2022.4.20
