### ISSUE TITLE
Key Pressed on Keyboard Do Not Represent Actual Characters Entered in Einstein

### ISSUE THREAD

**Issue by eggfreckles** [pguyot/Einstein#20]
I am sure this is already documented, as I remember reading it somewhere, but keys pressed on a keyboard for not represent the actual characters entered Einstein for Ubuntu. I am sure this is configured in the X1ll libraries somewhere. I will keep looking.

Keep up the great work Steven F.

**Comment by MatthiasWM** [comment]
Yes, this is documented as a bug since 2007 ;-) . Would be nice to fix.

**Comment by MatthiasWM** [comment]
This is fixed on all platforms now.
