### ISSUE TITLE
Can't compile K lib on Fedora 25

### ISSUE THREAD

**Issue by chuma** [pguyot/Einstein#23]
I am getting this error when I attempt to build the K lib on Fedora 25:
`C++ build.LINUX/TFileStream.cp.o `
`    ../../../K/Streams/TFileStream.cp: In member function ‘virtual void TFileStream::SetCursor(KSInt64, TRandomAccessStream::ECursorMode)’:`
`    ../../../K/Streams/TFileStream.cp:232:40: error: invalid cast from type ‘KSInt64 {aka TSInt64}’ to type ‘off_t {aka long int}’`
`      int theErr = ::fseeko( mFile, (off_t) inPos, whence );`

`	cc -c -o "build.LINUX/TFileStream.cp.o" -I/opt/local//include -DTARGET_OS_LINUX=1 -Wall -Wno-multichar -Wno-unknown-pragmas -W -Wfloat-equal -Wshadow -Wpointer-arith -Wwrite-strings -Wconversion  -O  -I"../../.." -I"../../../_Tests_" -I"../../../_Tests_/Tests" "../../../K/Streams/TFileStream.cp"`

I suck at C and C++, so someone please help me.  I don't understand why this is cast doesn't _just work_. 

I've had to hack the Jamfile for K a bit because it is doing a terrible job of realizing I am not compiling for a Raspberry Pi :(  Specifically I removed the `-m32` flag from the compiler flags, because I am compiling on a 64-bit platform.  With `-m32` many more things are broken.

This is literally the only object in K lib that won't build for me.

My system versions:

`Linux marceline 4.9.8-201.fc25.x86_64`
`gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)`
`glibc 2.24`

**Comment by pguyot** [comment]
The KDefinitions.h believes your machine is 32bits and tries to emulate 64bits integers with a structure, while at some other point in the code it passes such an integer to fseeko which doesn't like it.

The detection code just did not work. And indeed, KDefinitions.h should definitely be improved and cleaned up to handle modern platforms.

You can try to fix it or, as a workaround, simply define HAS_C99_LONGLONG to 1
https://github.com/pguyot/Einstein/blob/master/K/Defines/KDefinitions.h#L621

You probably should also set KUIntPtr to KUInt64.

**Comment by chuma** [comment]
Hi Paul!

The workaround worked.  Thanks.  Agreed, this could definitely be improved.

**Comment by panicsteve** [comment]
@chuma Did you use -starget=linux like in the Ubuntu instructions? IIRC, I think that removes the -m32 flag and defines HAS_C99_LONGLONG. If that didn't work for you, I'll spin up a fedora VM and see if I can fix the Jamfile.
