### ISSUE TITLE
Where does the REx source live?

### ISSUE THREAD

**Issue by panicsteve** [pguyot/Einstein#26]
I just realized I don't have it, and I don't think I've ever seen it.

Does it exist in a public repository anywhere?  Should it be merged into the Einstein repository?

**Comment by jake-b** [comment]
Its in the 'Drivers' directory: 
https://github.com/pguyot/Einstein/tree/master/Drivers

**Comment by panicsteve** [comment]
Oh wow, I completely missed it. Thanks!
