### ISSUE TITLE
Build Error "Unknown MacOS X architecture" when building for iOS

### ISSUE THREAD

**Issue by joedemo42** [pguyot/Einstein#27]
MacOS X 10.11.6, Xcode 8.2.1, Target iOSEinstein, Signing automatically managed with dev cert, building for either generic iOS Device or my very specifc iPad mini 2.

When building the freshly checked out code, the build stops right [here](https://github.com/pguyot/Einstein/blob/master/K/Defines/KDefinitions.h#L277).

**Comment by panicsteve** [comment]
Looks like my bad.  I added arm64 to the list of supported architectures in the project so the OS wouldn't display the "iOSEinstein May Slow Down Your iPhone" error on launch (which shows for 32-bit only apps on iOS 10).  But after a clean rebuild, I get the same error as you.

For now, go to Build Settings > iOSEinstein > Valid Architectures and remove arm64 from the list.

I will work on an actual fix.

**Comment by joedemo42** [comment]
Awesome! Thanks for the super-fast help.

**Comment by panicsteve** [comment]
Fixed in 19c4a67 by updating KDefinitions.h to recognize __arm64__ and config appropriately.
