### ISSUE TITLE
iOS Einstein broken on iOS 11

### ISSUE THREAD

**Issue by js6004** [pguyot/Einstein#30]
Hi,
I’m using the developer’s version of iOS 11 and ioseinstein doesn’t work on it.
Any ideas?

**Comment by panicsteve** [comment]
Just tried running it on the simulator with iOS 11 and it stops with a black screen with this logged to the console:

```2017-06-14 15:30:09.023565-0700 iOSEinstein[15077:1064863] Warning: Attempt to present <UIAlertController: 0x7f8d75026000> on <iEinsteinViewController: 0x7f8d73503590> whose view is not in the window hierarchy!```

This is trying to bring up the alert about the missing ROM file, I believe.

**Comment by panicsteve** [comment]
Changing `iEinsteinViewController`'s `viewDidLoad` to `viewDidAppear` fixes the missing ROM file alert.  But after placing the ROM file in the correct location, the emulator is booting to a black screen.  The Newton startup chime is audible.

**Comment by panicsteve** [comment]
Adding an additional call to `setNeedsDisplay` in `iEinsteinView` when `setScreenManager` is called seems to get the Newton display to reappear on iOS 11 Developer Preview.  Could @js6004 confirm this works?

**Comment by js6004** [comment]
Hi Steven,
I don’t know much about what you’re talking about. I code in Livecode. Could you explain in detail what you did to get it to work? Or is there a new version that you could compile that works that you could send me?
Thanks for responding so quickly!
Janet

**Comment by panicsteve** [comment]
Ah, sorry, I mistakenly thought you had an Einstein build environment set up.

AFAIK, I don't think I can easily just give you a pre-built binary, as iOS binaries have to be signed and can only be installed on a provisioned device.

If you have a Mac with Xcode, you should be able to clone the source from here on GitHub, build and run it in the iOS Simulator.  To run it on actual iOS hardware, you'll need an Apple Developer account, signing certificate, and provisioned device.

I'm going to close the bug, as I'm pretty sure the bug itself is resolved.
