### ISSUE TITLE
Blank screen iPad Pro 9.7" iOS 10.3.2

### ISSUE THREAD

**Issue by mwvaughn** [pguyot/Einstein#31]
I've built Einstein under XCode and run both under emulation and on my physical iOS device. In both cases, despite having a working ROM, all I can get is a blank green/black screen. 

![screen shot 2017-08-15 at 9 52 54 pm](https://user-images.githubusercontent.com/723861/29345597-78dd68d0-8205-11e7-9995-80f25a3c2479.png)

**Comment by panicsteve** [comment]
@MatthiasWM It's blocking at the select() call on line 888 of TVoyagerManagedSerialPort.cp on iOS 10.3.  Works fine on iOS 11 betas, though.  Any ideas?

**Comment by mwvaughn** [comment]
I tried building against an older iOS target to see if there was a regression introduced in 10.X (I don't know how active iOS development is and thus whether the latest OS had been tested) and I got the same error. I also, just for laughs, tried building against iPhone 5 & 6 as those are my actual installation targets for this application once I get it going.

**Comment by MatthiasWM** [comment]
OK, I looked at the code mentioned, and the "select()" call seems to be quite in order. It is a blocking call, but it only blocks one of many threads that Einstein starts to emulate hardware. This should not be related to the actual ROM code execution. I would think that the issue is somewhere else.

I am not very versed at iOS development at all. I may be able to set up a virtual iPad, but I don;t own a physical iOS device (and I don;t intend to buy one thanks to the restrictive Apple store that has repeatedly kicked Einstein out).

**Comment by MatthiasWM** [comment]
BTW: how do I upload the ROM into a virtual iOS device?

**Comment by panicsteve** [comment]
@MatthiasWM When you run it without a ROM, it will log a path to the Xcode Console that tells you where to place the ROM and what it should be named.

If you can't figure out what's causing the hang, I can (try to) help!

**Comment by MatthiasWM** [comment]
iEinsteinViewController::initEmulator is never called. The Sandbox implementation seems to wait for iEinsteinViewController::viewDidAppear, which is not called, at least not before iEinsteinAppDelegate::applicationDidBecomeActive complains about missing resources and quits.

I don't know anything about these sandboxes or the order in which ViewControllers call, or AppDelegates can be made to wait for the availability of a display. So, sorry, I have to leave the task of fixing this bug to an iOS expert.

**Comment by panicsteve** [comment]
I moved the initEmulator call from viewDidAppear to viewWillAppear which, as the name suggests, is called earlier.  That seems to have gotten things firing in the right order so Einstein boots under 10.3 once again.

**Comment by MatthiasWM** [comment]
Great. Thank you. Works for me!
