### ISSUE TITLE
Ios11.1

### ISSUE THREAD

**Issue by js6004** [pguyot/Einstein#35]
Einstein won’t launch under iOS 11.1. Can someone fix it?

**Comment by panicsteve** [comment]
11.1 just got released today, so I'll take a look when I have a free moment.

**Comment by panicsteve** [comment]
I can't reproduce this issue on an iOS 11.1 simulator on Xcode 9.1.

Are you sure it's not this issue:

https://github.com/pguyot/Einstein/issues/30

or this one:

https://github.com/pguyot/Einstein/issues/31

If so, you may need to install a more recently compiled binary.

**Comment by js6004** [comment]
Dear Steven,
Thank you for your fast response. I finally was able to get iosEinstein working. I don’t know what the real problem was.

Take Care,

Janet
