### ISSUE TITLE
Android build instructions please?

### ISSUE THREAD

**Issue by chuma** [pguyot/Einstein#39]
## Basic Information

* Platform (Mac, iOS, Android, Linux, etc): **Android**
* Built from source? (yes/no): **I would like to**
    * source branch/revision ID: **master**

## Description of issue
I cannot for the life of me figure out how to use Android Studio to build Einstein.

Some basic instructions in the wiki would be appreciated, eg. how to open the project in Android Studio, what SDK package are required, how to "just build" an APK.

## Expected behaviour
* People can build Einstein for Android easily

## Steps to reproduce issue
1. Download Android Studio
2. Check out Einstein code
3. ???
4. Profit!

**Comment by MatthiasWM** [comment]
Android build instructions are now at the bottom af the [[Build Instructions]] wiki page
