### ISSUE TITLE
MSWindows 2018 Release

### ISSUE THREAD

**Issue by MatthiasWM** [pguyot/Einstein#44]
Port serial port emulation, ethernet card emulation, and user interface changes to the Microsoft Windows implementation. 

If we stick with FLTK as the GUI, I could also port the Monitor.

Also, we should probably upgrade to the current Visual Studio release.

**Comment by MatthiasWM** [comment]
Meh. Looking at the VisualC project. This is not working at all anymore. It will have to be rewritten entirely.

**Comment by chuma** [comment]
Apparently VS2017 has support for CMake projects, and CMake can generate projects for VS6 and up, so maybe that will help?  I will try it out.

**Comment by chuma** [comment]
I can pull my CMake project into VS 2017 and attempt to build it - so that's something.

However, there are many, many compile errors.

**Comment by MatthiasWM** [comment]
The  matt2020 branch now has everything to make the VisualC 2019 environment churn out a working version of Einstein, including an FLTK UI that is now the same on all platform and finally maintainable.
