### ISSUE TITLE
Linux 2018 release

### ISSUE THREAD

**Issue by MatthiasWM** [pguyot/Einstein#45]
Porting the GUI code from MSWindows to Linux as well (the command line version must remain). Port serial and network emulation.

**Comment by MatthiasWM** [comment]
I just looked at the MSWindows version. The IDE files are hopelessly out of date. The FLTK related files may or may not be in relation to ten years of changes in the core code. I'll investigate further on MSWindows.

**Comment by chuma** [comment]
I started a branch here: https://github.com/chuma/Einstein/tree/Linux-FLTK where I updated TFLApp and TFLScreenManager already.

**Comment by MatthiasWM** [comment]
oh, oh, sorry, I am so behind. I was looking at the code, but I did not have time to update anything. Linux and MSWindows code with FLTK should be pretty much the same in the end. It should also just run on MacOS X as well, using the same FLTK code. Sound of course is platform dependent, and some of the network code. 

I won't be able to write anything this weekend, maybe next... .

**Comment by chuma** [comment]
Update: I am well on my way to having a nice Flatpak based package for a Linux release.

**Comment by MatthiasWM** [comment]
Looks great! BasiliskII emulation has a few additional tricks which don't seem to interfere here. If BasiliskII is not available on Linux, it may make sense to write a more generic driver.

I must at some point add to the documentation, that all this probably only works with the 717006 ROM!

Recaching the ROM when the patches change would be a very useful feature.

**Comment by chuma** [comment]
I've used BasiliskII on Linux for a long time. I can connect Einstein to it as well, all I tried was an Inspector connection.

**Comment by MatthiasWM** [comment]
@chuma Hi Victor, thanks for all you help. I have started reading through your code, but ended up rewriting a lot myself. If you have time, could you look at the matt2020 branch and check, which parts of you source code could be merged into it? FLTK and CMake run pretty well for me now.

I know nothing about Flatpacks, but it seems to be the way to go. Can you help me set that up?
