### ISSUE TITLE
Won't run on Yosemite 10.10.3

### ISSUE THREAD

**Issue by thomasqbrady** [pguyot/Einstein#5]
Built fine. Launches fine. I choose the rex file and click start and it quits. Am I doing something wrong?

**Comment by pguyot** [comment]
Could you provide us with a relevant system log excerpt or a crash log?

**Comment by panicsteve** [comment]
I suspect you may be getting prompted for the ROM file and are choosing the REx file by mistake? (The ROM cannot be distributed as Apple still owns the copyright)

**Comment by thomasqbrady** [comment]
Exactly right, @panicsteve, I didn't read the directions correctly. When I read "for your convenience," I guess I turned my brain off.

Hadn't noticed you were on this project, but now I think I'd be more shocked if you hadn't been involved.

**Comment by thomasqbrady** [comment]
Booting...
