### ISSUE TITLE
Hanging at end of startup sound on iOS simulator

### ISSUE THREAD

**Issue by panicsteve** [pguyot/Einstein#53]
## Basic Information

Boots to Newton logo splash screen, then hangs playing end of startup chime.

## Description of issue

Boots to the Newton logo splash screen and plays the startup chime, but hangs at (what I guess is) the last output buffer of the sound, repeatedly logging ```PMainSoundDriver::OutputIntHandler``` to the Xcode console.

The simulator continues to emit a low buzzing/droning sound through the audio output, which I'm guessing is the last buffer of the startup chime playing on a loop.

## Expected behaviour

Startup sound should finish playing, boot should continue to backdrop / setup assistant.

## Steps to reproduce issue

I pulled the current master (5714557) and built for iOS, ran on iPhone X simulator.

This worked until fairly recently, so I wonder if it was one of the recent commits related to sound.  If necessary, I can try rolling back to earlier commits to see if it starts working again.

**Comment by panicsteve** [comment]
Update:

Going back through the commit history, f700170 is the last commit that I can build that **does not** have this issue.

The next batch of commits (809bbf3 ... f60a6b1) all have build errors.

The next commit after that (988cda0) does build, and the problem is present.

So, the problem was introduced in one of @MatthiasWM's commits for the serial port work, as far as I can tell.

**Comment by MatthiasWM** [comment]
Oh no, it's me :-( . Hmm, I tried to make the serial port stuff as transparent for the system as possible, but I obviously failed. I should have time tonight or tomorrow to find the culprit. I do have an idea already... . As I am not very versed in iOS, does it make sense to emulate the serial port? And if so, how would the serial port present itself to the world?

**Comment by panicsteve** [comment]
I don't know what changed but I can now reproduce this on the macOS build too.  I swear it was only happening on the iOS build yesterday.  Behavior is the same.  If you uncomment ```mLog = new TStdOutLog();``` in TCocoaAppController.mm, you can see ```PMainSoundDriver::OutputIntHandler``` being logged repeatedly to the console, as with the iOS build.

So, unfortunately, just removing serial port support from iOS won't fix it. 

I'll keep poking around but I'm not sure exactly what I'm looking for, and nothing jumped out at me in the diff of a working and non-working commit...

**Comment by panicsteve** [comment]
If nothing else, I can confirm that simply commenting out the ROM patch in line 332 of Emulator/Serial/TBasicSerialPortManager.cp eliminates the problem and makes the system boot normally again:

``` TJITGenericPatchFindAndReplace gEnableSerialPort(0x00800634, 0x00900000,
												 (KUInt32[]){2, 'extr', 0},
												 (KUInt32[]){1, '~xtr'},
												 "Enable 'extr' serial port.\n");```

**Comment by MatthiasWM** [comment]
The ROM Patch should not apply to iOS, unless the macro `TARGET_OS_MAC` is also set for iOS. On MacOS, removing the patch disables the entire serial port emulation, so I assume you refer to MacOS. Do you use the 717006 ROM? The patch may apply wrong on other ROMs.

**Comment by panicsteve** [comment]
I can confirm by dropping an `#error` in the `#if TARGET_OS_MAC` block that TARGET_OS_MAC is set to 1 for the iOS build.

**Comment by panicsteve** [comment]
As far as I can tell, the issue is timing sensitive.  Although the problem is fairly consistently reproducible on iOS, it is intermittent on macOS, and things happen in different ways depending on whether I'm running in the debugger.

Upon reaching the end of the startup chime, you can see the CoreAudio driver requesting more data from the Newton by calling `TInterruptManager::RaiseInterrupt(0x1000)` over and over again.  Whatever signal is supposed to tell CoreAudio that it can stop outputting audio never arrives, the last buffer of samples repeats forever (buzzzzzz), and the emulator never proceeds past the Newton logo startup screen.

So, I think we have some sort of race between CoreAudio, the emulator thread, and the interrupt manager thread, and it only shows up when the ROM injection for the 'extr' serial port is added.  Could be a doozy to debug and I'm feeling out of my league.

**Comment by chuma** [comment]
If you can run Einstein with logging enabled and reproduce the issue on macOS, and post the log here, that might be helpful.

However I think the problem is not with Matthias' code but with the CoreAudio driver.   When I was writing the PulseAudio output driver, I had this problem where:

1. Newton: sends last frames of sound.
2. Emulator: receives last part of sound, raises interrupt
3. Newton: asks Emulator "Is output running?"
4. Emulator: replies with "yes!"
5. Newton: sends zero-length sound to play.
6. Emulator: WTF? Raises interrupt
7. Newton: GOTO 3, basically

What the Newton side should be doing is calling StopOutput, but it never does.  The CoreAudio driver either isn't calling RaiseOutputInterrupt correctly, or it needs to be smarter.

What worked for me was, when PulseAudio receives a ScheduleOutput call with zero frames, call StopOutput.

Why this is happening now is, like you said, probably due to timing.

**Comment by panicsteve** [comment]
I have seen that exact scenario (ScheduleOutput receiving a 0-length buffer) in some of my debugging runs, but not consistently.  Things like adding/removing logging calls and stopping in the debugger affect the timing and thus the execution path.

Calling StopOutput on a 0-length buffer is probably a good workaround, but I'm a little concerned that it hides the symptom without fixing the root cause.  But it may also be harmless.  I don't feel versed enough in what's happening on the NewtonOS side to say if we ought to be concerned that this problem could manifest elsewhere in other interrupt-driven/DMA functions.

**Comment by MatthiasWM** [comment]
I know that this issue is many years all, but since I have all relevant developers on this list:

The iOS version compiles fine again since a few days ago. It does run on my iPhone 13 Max Pro and seems to run on other phones too, **however** it does not run in the simulator and bail before I even get to the debugger (MacBook Pro M1). Could anyone look at that please?

**Comment by panicsteve** [comment]
> The iOS version compiles fine again since a few days ago. It does run on my iPhone 13 Max Pro and seems to run on other phones too, **however** it does not run in the simulator and bail before I even get to the debugger

@MatthiasWM Is this the crash you're seeing?

```
Thread 0 Crashed:
0   dyld 0x11415aa78 _dyld_debugger_notification + 0
1   dyld 0x1141788e7 lldb_image_notifier(dyld_image_mode, unsigned int, dyld_image_info const*) + 190
2   dyld 0x11415f9a8 dyld4::prepareSim(dyld4::RuntimeState&, char const*) + 885
3   dyld 0x11415e6de dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 244
4   dyld 0x11415e4b4 start + 388
```

This appears to be lldb crashing during dylib loading (in the dyld process), long before our main(), which is... weird.

I only looked at it for a second so I'm not sure what's going on yet.  I'm wondering if some x86_64 arch code is somehow getting linked into the iOS (arm) build?

**Comment by MatthiasWM** [comment]
@panicsteve I did clean the building folder beforehand to make it build from scratch,  but I get (simulator only). It does run on my physical machine. Weird.
```
dyld`_dyld_debugger_notification:
->  0x107ed9b48 <+0>:  ret    
    0x107ed9b4c <+4>:  udf    #0x0
    0x107ed9b50 <+8>:  udf    #0x0
    0x107ed9b54 <+12>: udf    #0x0
    0x107ed9b58 <+16>: udf    #0x0
    0x107ed9b5c <+20>: udf    #0x0
```

**Comment by panicsteve** [comment]
Huh, it also runs fine in the simulator, as long as it's _not_ running under the debugger.  That is super weird.  I'll ask around here if anyone has any theories.

**Comment by MatthiasWM** [comment]
Cool, thank you!

**Comment by panicsteve** [comment]
Commit 26b7bbdcc9b0e9cb9854202abd793922efde73ac should fix this.  There were a couple of obsolete / misconfigured settings in the iOS target.  It now runs as far as the "missing ROM" alert on the simulator on my Xcode 13.2.1.  Big thank you to my coworker Michael for digging up the relevant StackOverflow post.  :)

**Comment by MatthiasWM** [comment]
Great resource. I mean your coworker. But StackOverflow as well ;-)

**Comment by MatthiasWM** [comment]
Is the original sound problem still an issue?

**Comment by MatthiasWM** [comment]
I believe that this was fixed.
