### ISSUE TITLE
MacOS package installs to /Users/matt/Applications, has no title

### ISSUE THREAD

**Issue by chuma** [pguyot/Einstein#57]
## Basic Information

* Platform (Mac, iOS, Android, Linux, etc): Mac OS 10.13.4.  
* Built from source? (yes/no): no
    * If no, release version: 2018.5.extr

Language & Region are set to English - Canada.

## Description of issue

The app ends up installed to `/Users/matt/Applications` instead of the current user's Applications folder.

The installer never mentions the actual name of the application, it seems to not be set at all.  This results in strange looking dialog messages such as "Do you want to move the '' installer to the Trash?"

## Expected behaviour

The application is installed in the current user's Applications folder.
The installer uses the name of the application.

## Steps to reproduce issue

Download 2018.5.extr Einstein.pkg from the releases section.

Double-click it from its download location to run the installer.

After installing, run Einstein (you might have to use Spotlight to find it in order to launch it), then open a terminal and run `ps ax |grep Einstein` and note the path to the Einstein application starts with `/Users/matt`

**Comment by panicsteve** [comment]
There's no compelling reason for us to package Einstein in an installer at all.  Plain old application on a disk image is preferable for macOS apps.

**Comment by MatthiasWM** [comment]
OMG, yes. I have no clue what made my choose the installer when I created that package. This really needs to be reversed. Not sure if I can do it today, but AAAAAAH, sorry!

**Comment by MatthiasWM** [comment]
This should no longer happen.
