### ISSUE TITLE
UserManual.pdf missing from repo

### ISSUE THREAD

**Issue by panicsteve** [pguyot/Einstein#6]
The .tex source appears to have survived the move from Google Code, but the PDF is missing.

It is referenced on the wiki page for dumping the ROM:

https://github.com/pguyot/Einstein/wiki/Dumping-The-Rom

**Comment by pguyot** [comment]
I definitely do have the binary that was generated from the .tex file. However, does it really belong here? GitHub deprecated downloads and this isn't a release file…

**Comment by splorp** [comment]
I think it’s useful to have properly formatted documentation available, particularly for users that perhaps cannot work with sources like .tex files.

GitHub still supports binaries, regardless of their stance on downloads.

Why not create a documentation directory or similar?

**Comment by panicsteve** [comment]
It might make sense to integrate the documentation into the GitHub wiki for this project. This would make it easy for other project members to update moving forward, and easier to find for people just experimenting with running Einstein. 

If you agree and can supply the file in plain text, I'm willing to help convert it into markdown wiki pages.

**Comment by pguyot** [comment]
Noted. We do have a Documentation directory, where the source code for the documentation lies (.tex and images), now along with the generated PDF that was on Google Code.

**Comment by pguyot** [comment]
@panicsteve I am all for converting the documentation to the Wiki, at least the essential parts such as getting a ROM.

**Comment by morgant** [comment]
You can [clone & edit GitHub wikis locally](https://help.github.com/articles/adding-and-editing-wiki-pages-locally/), so presumably you could put the PDF in there as well.

**Comment by splorp** [comment]
+1

**Comment by panicsteve** [comment]
I have copied the information on dumping the ROM from the UserManual.pdf to the corresponding wiki page.
