### ISSUE TITLE
Trying to run on iOS iPad Pro with Apple Pencil

### ISSUE THREAD

**Issue by bbellina** [pguyot/Einstein#60]
## Basic Information
I am trying to get Einstein to run on an iPad Pro with Apple Pencil. I have tried with both the unna debug files and my own ROM created from my MP 2100 and get the same results. On Mac OS X it works but on iOS the initial Newton startup screen is displayed and chime played but then it freezes.

* Platform (Mac, iOS, Android, Linux, etc): iOS11.4.1 
* Built from source? (yes/no): Yes
    * If yes, source branch/revision ID: 
    * If no, release version:

## Description of issue
Freezes after displaying startup screen on iPad Pro.  The last thing I see in Xcode is a message that it is checking the display size.

**Comment by txomin-jimenez** [comment]
It looks like current iOS build is broken: https://github.com/pguyot/Einstein/issues/53   
You can make it work for iOS if you build it from this older commit: https://github.com/pguyot/Einstein/commit/f700170716259a4e1a2fc0a72a65b864a04b16a8

**Comment by bbellina** [comment]
I posted about my attempt to get Einstein working on my iPad in a blog post [here](http://bbellina.blogspot.com/2018/09/newton-messagepad-ipad-quest.html) and received a reply that commenting out the ROM patch in line 332 of Emulator/Serial/TBasicSerialPortManager.cp would resolve the problem. I have done that and it did correct the issue. Using the Apple Pencil with Einstein on my iPad Pro is working well so far.  It would be really great if Einstein could use the iOS clock and handle current dates.

**Comment by bbellina** [comment]
Closing the issue.
