### ISSUE TITLE
Build fail: Two files mentioned in Linux Jamfile not in master branch

### ISSUE THREAD

**Issue by toxicgumbo** [pguyot/Einstein#69]
Two files mentioned in `Einstein/_Build_/Jam/Jamfile` don't exist in the master branch.  These can be found on lines 245-246:

```
COMMON_CPP_SOURCES      += "$(BASE)Emulator/JIT/Generic/TJITGenericRetarget.cp" ;
COMMON_CPP_SOURCES      += "$(BASE)Emulator/JIT/Generic/TJITGenericRetargetMap.cpp" ;
```

Commented out, the Einstein binary will build successfully in Ubuntu 18.04.3 minimal install, 32-bit, in VirtualBox 6.0.14 on Mac OS 10.15.1.  

The build instructions I followed:

[https://github.com/pguyot/Einstein/wiki/Build-Instructions](https://github.com/pguyot/Einstein/wiki/Build-Instructions)

**Comment by MatthiasWM** [comment]
Please remove the reference to those files from the JamFile. They should not be needed any longer. Sorry about that.

**Comment by toxicgumbo** [comment]
Pull request issued for file reference removal.  Review and approval requested.

**Comment by chuma** [comment]
@toxicgumbo is there a reason you didn't build Einstein using CMake?
[Linux-(x86)-build-and-run-instructions](https://github.com/pguyot/Einstein/wiki/Linux-%28x86%29-build-and-run-instructions)

**Comment by toxicgumbo** [comment]
Fair question. Likely an oversight after having jumped back and forth between build docs amidst other responsibilities.  This explains why I remembered it being less grumpy months ago :-)  

I'll re-approach the preferred method (which you've linked to) in 32-bit minimal Ubuntu 18.04 (https://help.ubuntu.com/community/Installation/MinimalCD) and see if there was something that led me to go deprecated.
