### ISSUE TITLE
Issue with compiling for Android

### ISSUE THREAD

**Issue by eisnerguy1** [pguyot/Einstein#7]
I tried compiling Einstein for Android and I ran into some issues of "TSymbolList.h" not existing.  I've included the Terminal output below:

Last login: Sat Oct  3 17:22:38 on ttys000
eisnerguy1s-MacBook-Pro:~ eisnerguy1$ cd /Users/eisnerguy1/Applications/Einstein/Einstein-master/_Build_/EclipseAndroid 
eisnerguy1s-MacBook-Pro:EclipseAndroid eisnerguy1$ /Users/eisnerguy1/Downloads/_Updates/android-ndk-r10e/ndk-build
[armeabi] Compile++ arm  : einstein <= AndroidGlue.cp
jni/../../../app/AndroidGlue.cp: In function 'void Java_com_newtonforever_einstein_jni_Native_setNewtonID(JNIEnv_, jobject, jstring)':
jni/../../../app/AndroidGlue.cp:281:37: warning: format '%x' expects argument of type 'unsigned int_', but argument 3 has type 'KUInt32\* {aka long unsigned int_}' [-Wformat=]
   sscanf(cID, "%08x%08x", &id0, &id1);
                                     ^
jni/../../../app/AndroidGlue.cp:281:37: warning: format '%x' expects argument of type 'unsigned int_', but argument 4 has type 'KUInt32\* {aka long unsigned int_}' [-Wformat=]
[armeabi] Compile++ arm  : einstein <= TAndroidApp.cp
[armeabi] Compile++ arm  : einstein <= TAndroidScreenManager.cp
[armeabi] Compile++ arm  : einstein <= TARMProcessor.cp
jni/../../../Emulator/TARMProcessor.cp:43:25: fatal error: TSymbolList.h: No such file or directory
 #include "TSymbolList.h"
                         ^
compilation terminated.
make: *_\* [obj/local/armeabi/objs/einstein/Emulator/TARMProcessor.o] Error 1
eisnerguy1s-MacBook-Pro:EclipseAndroid eisnerguy1$

**Comment by panicsteve** [comment]
I've never built the Android build, but TSymbolList lives in the Monitor/ folder.  Your development environment needs to be configured to look in project sub-folders such as Monitor/ for include files.

**Comment by MatthiasWM** [comment]
Commited a basic Android Studio setup. Could anyone try this please and fix the runtime issues?
