### ISSUE TITLE
Adding related links and news mentions

### ISSUE THREAD

**Issue by splorp** [pguyot/Einstein#9]
Hello everyone.

I think it would be beneficial to have a list of links related to the Einstein project, along with mentions of the project on other sites. Where would be the best place to compile these links?

On one hand, I think adding a few relevant links to the README would provide visitors some additional context regarding the project right up front. Otherwise, we could add a page to the wiki specifically for external resources and related links.

What are your thoughts?

**Comment by panicsteve** [comment]
IMHO if the link is useful to the person finding the project for the first time, add it to the README.md. For just collecting links to mentions that aren't directly related to "here's how to help with the project", those should probably go on their own wiki page.

**Comment by splorp** [comment]
Closing this issue reminded me to set up a wiki page as suggested.

https://github.com/pguyot/Einstein/wiki/Related-Links-&-Information

Thanks for the nudge, Steven!
