### ISSUE TITLE
matt2020: Compilation issue on Ubuntu 20.04 x86_64

### ISSUE THREAD

**Issue by jacexpo** [pguyot/Einstein#95]
## Basic Information

* Platform (Mac, iOS, Android, Linux, etc): Linux Ubuntu 20.04 x86_64 
* Built from source? (yes/no): Yes
    * If yes, source branch/revision ID: MATT2020 
    * If no, release version:

## Description of issue

Compilation issue 

/home/chrisr/Downloads/Einstein/Emulator/PCMCIA/TLinearCard.cpp: In member function ‘void TLinearCard::ImageInfo::flipByteOrder()’:
/home/chrisr/Downloads/Einstein/Emulator/PCMCIA/TLinearCard.cpp:733:17: error: ‘htonl’ was not declared in this scope
  733 |     pNameSize = htonl(pNameSize);
      |                 ^~~~~
/home/chrisr/Downloads/Einstein/Emulator/PCMCIA/TLinearCard.cpp: In member function ‘int TLinearCard::ImageInfo::read(FILE*)’:
/home/chrisr/Downloads/Einstein/Emulator/PCMCIA/TLinearCard.cpp:749:9: warning: unused variable ‘err’ [-Wunused-variable]
  749 |     int err = 0;
      |         ^~~
/home/chrisr/Downloads/Einstein/Emulator/PCMCIA/TLinearCard.cpp:753:10: warning: unused variable ‘buf’ [-Wunused-variable]
  753 |     char buf[sizeof(ImageInfo)];
      |          ^~~
/home/chrisr/Downloads/Einstein/Emulator/PCMCIA/TLinearCard.cpp: In member function ‘virtual int TLinearCard::Init(TPCMCIAController*)’:
/home/chrisr/Downloads/Einstein/Emulator/PCMCIA/TLinearCard.cpp:129:14: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
  129 |         fread(mMemoryMap, mImageInfo.pDataSize, 1, mFile);
      |         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/chrisr/Downloads/Einstein/Emulator/PCMCIA/TLinearCard.cpp:137:14: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
  137 |         fread(mCISData, mCISDataSize, 1, mFile);
      |         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/Einstein.dir/build.make:521: CMakeFiles/Einstein.dir/Emulator/PCMCIA/TLinearCard.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:104: CMakeFiles/Einstein.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

## Expected behaviour

I would have expected the compilation to continue

## Steps to reproduce issue

simple make - fails at this error

**Comment by MatthiasWM** [comment]
Please try the new instruction in BUILDING.md with the latest version of the GIT repo.

**Comment by MatthiasWM** [comment]
This should work now.
