### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by chrisparana** [pguyot/Einstein#98]
## Basic Information

* Platform (Mac, iOS, Android, Linux, etc): iPadOS
* Built from source? (yes/no): yes
    * If yes, source branch/revision ID: master 6e998633
    * If no, release version:

## Description of issue
I'm getting the following build errors:
iEinsteinViewController.mm:273:25: No matching constructor for initialization of 'TFlatROMImageWithREX'
iEinsteinViewController.mm:280:25: No matching constructor for initialization of 'TAIFROMImageWithREXes'
iEinsteinViewController.mm:303:24: Unknown type name 'TNullNetwork'

**Comment by MatthiasWM** [comment]
Thanks. There were some bigger changes over the last months, and the iOS build has not yet been updated. I will try to take a look at that today.

**Comment by MatthiasWM** [comment]
This should all be solved now, except for Android.
